"""Viktorina uchun bilim savollari.

Q(id, bo'lim, savol, [TO'G'RI javob, xato1, xato2, xato3], tushuntirish, ref)
  • birinchi variant — doim to'g'ri javob (ko'rsatishda aralashtiriladi)
  • ref — "📖 Batafsil" tugmasi ochadigan mavzu kaliti (shu bo'limdan)
  • Telegram so'rovnomasi cheklovlari: savol ≤ 300, variant ≤ 100, tushuntirish ≤ 200 belgi
"""


def Q(qid, sec, q, opts, explain, ref=None):
    return {"id": qid, "sec": sec, "q": q, "opts": opts, "explain": explain, "ref": ref}


QUESTIONS = [
    # ───────────── 🧠 Nerv tizimi ─────────────
    Q("n1", "nerv", "Bosh miyadan necha juft nerv chiqadi?", ["12 juft", "10 juft", "31 juft", "8 juft"],
      "Bosh miyadan 12 juft nerv chiqadi: I — hid bilish nervidan XII — til osti nervigacha.", "cn1"),
    Q("n2", "nerv", "Orqa miyadan necha juft nerv chiqadi?", ["31 juft", "12 juft", "33 juft", "24 juft"],
      "31 juft: 8 bo'yin, 12 ko'krak, 5 bel, 5 dumg'aza va 1 dum nervi.", "spinalcord"),
    Q("n3", "nerv", "Tanadagi eng yo'g'on va eng uzun nerv qaysi?",
      ["Quymich nervi", "Son nervi", "Adashgan nerv", "O'rta nerv"],
      "Quymich nervi (n. ischiadicus) barmoqdek yo'g'on, dumbadan tizza ostigacha boradi.", "sciatic"),
    Q("n4", "nerv", "Yuzdagi mimika muskullarini qaysi nerv boshqaradi?",
      ["Yuz nervi (VII)", "Uch shoxli nerv (V)", "Til osti nervi (XII)", "Qo'shimcha nerv (XI)"],
      "Yuz nervi barcha mimika muskullarini boshqaradi. Zararlansa — Bell falaji.", "cn7"),
    Q("n5", "nerv", "Diafragmani qaysi nerv harakatlantiradi?",
      ["Diafragma nervi (C3–C5)", "Adashgan nerv", "Qovurg'alararo nervlar", "Qo'shimcha nerv"],
      "Diafragma nervi C3–C5 segmentlaridan chiqadi: \"C3, 4, 5 — diafragmani tirik tutadi\".", "phrenic"),
    Q("n6", "nerv", "Tirsakni urib olganda \"tok urgandek\" sezgi qaysi nerv tufayli bo'ladi?",
      ["Tirsak nervi", "Bilak nervi", "O'rta nerv", "Qo'ltiq nervi"],
      "Tirsak nervi (n. ulnaris) tirsakda teri ostida, suyak ustidan juda yuza o'tadi.", "ulnar"),
    Q("n7", "nerv", "Karpal tunnel sindromida qaysi nerv siqiladi?",
      ["O'rta nerv", "Tirsak nervi", "Bilak nervi", "Mushak-teri nervi"],
      "O'rta nerv (n. medianus) kaft usti kanalidan o'tadi va u yerda siqilishi mumkin.", "median"),
    Q("n8", "nerv", "Neyronning signalni UZATUVCHI uzun o'simtasi nima deyiladi?",
      ["Akson", "Dendrit", "Sinaps", "Miyelin"],
      "Akson signalni uzatadi, dendritlar esa qabul qiladi.", "neuron"),
    Q("n9", "nerv", "Miyelinli nerv tolasida impuls qanday tezlikda o'tadi?",
      ["120 m/s gacha", "Atigi 1–2 m/s", "1200 km/s", "1 sm/s"],
      "Miyelin qobiq tufayli impuls 120 m/s gacha (≈430 km/soat) tezlikda o'tadi.", "myelin"),
    Q("n10", "nerv", "Harakat koordinatsiyasi va muvozanat markazi qaysi?",
      ["Miyacha", "Uzunchoq miya", "Peshona bo'lagi", "Gipotalamus"],
      "Miyacha harakatni muvofiqlashtiradi va muvozanatni saqlaydi.", "cerebellum"),
    Q("n11", "nerv", "Ko'rish markazi bosh miyaning qaysi bo'lagida joylashgan?",
      ["Ensa bo'lagi", "Peshona bo'lagi", "Chakka bo'lagi", "Tepa bo'lagi"],
      "Ko'rish — ensa bo'lagida, eshitish — chakkada, fikrlash — peshona bo'lagida.", "cerebrum"),
    Q("n12", "nerv", "\"Jang yoki qoch\" reaksiyasini qaysi tizim boshqaradi?",
      ["Simpatik nerv tizimi", "Parasimpatik nerv tizimi", "Miyacha", "Orqa miya reflekslari"],
      "Simpatik tizim yurakni tezlashtiradi, qorachiqni kengaytiradi, adrenalin chiqaradi.", "sympathetic"),
    Q("n13", "nerv", "Nafas olish va yurak urishini boshqaruvchi hayotiy markazlar qayerda?",
      ["Miya ustunida (uzunchoq miya)", "Miyachada", "Peshona bo'lagida", "Epifizda"],
      "Uzunchoq miyada nafas va yurak-qon tomir markazlari bor — shuning uchun u hayotiy muhim.", "brainstem"),

    # ───────────── 💪 Muskullar ─────────────
    Q("m1", "musk", "Odam tanasida taxminan nechta skelet muskuli bor?",
      ["600 dan ortiq", "206 ta", "~150 ta", "3000 dan ortiq"],
      "600 dan ortiq skelet muskuli tana vaznining ~40% ini tashkil etadi. 206 — suyaklar soni."),
    Q("m2", "musk", "Tanadagi eng katta (og'ir) muskul qaysi?",
      ["Katta dumba muskuli", "Sonning to'rt boshli muskuli", "Orqaning eng keng muskuli", "Katta ko'krak muskuli"],
      "Katta dumba muskuli eng katta; u o'tirgan joydan turish va zinaga chiqishni ta'minlaydi.", "glutmax"),
    Q("m3", "musk", "Tanadagi eng uzun muskul qaysi?",
      ["Tikuvchi muskul", "Sonning to'rt boshli muskuli", "Yelkaning ikki boshli muskuli", "Boldir muskuli"],
      "Tikuvchi muskul (~50 sm) yonbosh suyagidan katta boldir suyagigacha qiya o'tadi.", "sartorius"),
    Q("m4", "musk", "Tirsakni YOZUVCHI muskul qaysi?",
      ["Yelkaning uch boshli muskuli", "Yelkaning ikki boshli muskuli", "Yelka muskuli", "Deltasimon muskul"],
      "Triceps tirsakni yozadi, biceps esa bukadi — ular antagonistlar.", "triceps"),
    Q("m5", "musk", "Asosiy nafas muskuli qaysi?",
      ["Diafragma", "Qovurg'alararo muskullar", "Qorinning to'g'ri muskuli", "Katta ko'krak muskuli"],
      "Diafragma nafas olishning ~70% ini ta'minlaydi: qisqarganda pastga tushadi va o'pkaga havo kiradi.", "diaphragm"),
    Q("m6", "musk", "Mashhur \"kubiklar\" (six-pack) qaysi muskul?",
      ["Qorinning to'g'ri muskuli", "Qorinning ko'ndalang muskuli", "Tashqi qiyshiq muskul", "Orqaning eng keng muskuli"],
      "Qorinning to'g'ri muskulini pay to'siqlari 3–4 bo'lakka bo'ladi — ular \"kubik\" bo'lib ko'rinadi.", "rectusabd"),
    Q("m7", "musk", "O'z o'lchamiga nisbatan eng kuchli muskul qaysi?",
      ["Chaynov muskuli", "Boldir muskuli", "Katta dumba muskuli", "Ikki boshli muskul"],
      "Chaynov muskuli oziq tishlarda 70–90 kg gacha bosim hosil qiladi.", "masseter"),
    Q("m8", "musk", "Tanadagi eng kuchli va yo'g'on pay qaysi?",
      ["Axill payi", "Tizza qopqog'i payi", "Ikki boshli muskul payi", "Bilak payi"],
      "Axill payi yugurganda tana vaznidan 8–12 marta ko'p yukni ko'taradi.", "achilles"),
    Q("m9", "musk", "\"Tabassum muskuli\" deb qaysi muskulga aytiladi?",
      ["Katta yonoq muskuli", "Lunj muskuli", "Og'izning aylana muskuli", "Chakka muskuli"],
      "Katta yonoq muskuli og'iz burchagini yuqoriga-tashqariga tortadi.", "zygomatic"),
    Q("m10", "musk", "Ichki a'zolar devoridagi, ixtiyorsiz qisqaradigan muskul turi qaysi?",
      ["Silliq muskul", "Skelet muskuli", "Ko'ndalang-targ'il muskul", "Pay"],
      "Muskulning 3 turi: skelet (ixtiyoriy), silliq (ichki a'zolarda) va yurak muskuli."),
    Q("m11", "musk", "Qo'lni yon tomonga ko'taruvchi asosiy muskul qaysi?",
      ["Deltasimon muskul", "Trapetsiyasimon muskul", "Ikki boshli muskul", "Rombsimon muskul"],
      "Deltasimon muskulning o'rta qismi qo'lni yonga 90° gacha ko'taradi.", "deltoid"),
    Q("m12", "musk", "Qaysi muskul \"ikkinchi yurak\" deb ataladi?",
      ["Kambalasimon muskul", "Diafragma", "Katta dumba muskuli", "Oldingi katta boldir muskuli"],
      "Kambalasimon muskul qisqarganda oyoq venalaridagi qonni yurakka haydaydi.", "soleus"),
    Q("m13", "musk", "Muskul qisqarishini ta'minlovchi asosiy oqsillar qaysilar?",
      ["Aktin va miozin", "Keratin va kollagen", "Gemoglobin va albumin", "Insulin va glyukagon"],
      "Miofibrillalardagi aktin va miozin iplari bir-biri ustida sirpanib, muskulni qisqartiradi."),

    # ───────────── 🧴 Teri, soch va tuklar ─────────────
    Q("t1", "teri", "Odam tanasidagi eng katta a'zo qaysi?", ["Teri", "Jigar", "O'pka", "Bosh miya"],
      "Teri maydoni 1,5–2 m², u tana vaznining ~16% ini tashkil etadi.", "skinfunc"),
    Q("t2", "teri", "Epidermis necha qavatdan iborat?", ["5 qavat", "3 qavat", "2 qavat", "7 qavat"],
      "Bazal, tikanakli, donador, yaltiroq va shox qavatlar.", "epidermis"),
    Q("t3", "teri", "Faqat kaft va oyoq tagida bo'ladigan epidermis qavati qaysi?",
      ["Yaltiroq qavat", "Shox qavat", "Bazal qavat", "Donador qavat"],
      "Yaltiroq qavat faqat terisi qalin joylarda — kaft va oyoq tagida bo'ladi.", "epidermis"),
    Q("t4", "teri", "Epidermis taxminan qancha vaqtda to'liq yangilanadi?",
      ["~28 kunda", "~1 yilda", "~3 kunda", "~7 yilda"],
      "Bazal qavatdagi hujayralar yuqoriga ko'tarilib, ~4 haftada shox qavat bo'lib to'kiladi.", "epidermis"),
    Q("t5", "teri", "Teri va sochga rang beruvchi asosiy pigment qaysi?",
      ["Melanin", "Gemoglobin", "Keratin", "Kollagen"],
      "Melaninni melanotsitlar ishlab chiqaradi; u terini UF nurlardan ham himoya qiladi.", "melanin"),
    Q("t6", "teri", "Boshda taxminan nechta soch bor?",
      ["100–150 ming", "10–15 ming", "1 million", "5 ming"],
      "Boshda ~100 000–150 000 soch bor; butun tanada ~5 million soch follikulasi.", "hairstruct"),
    Q("t7", "teri", "Soch qanday tezlikda o'sadi?",
      ["Oyiga ~1–1,5 sm", "Kuniga ~1 sm", "Yiliga ~1 sm", "Oyiga ~5 sm"],
      "Soch oyiga ~1–1,5 sm, yiliga ~15 sm o'sadi.", "hairgrowth"),
    Q("t8", "teri", "Sochning O'SISH bosqichi qanday ataladi?", ["Anagen", "Katagen", "Telogen", "Lanugo"],
      "Anagen (o'sish, 2–7 yil) → katagen (o'tish) → telogen (dam olish, so'ng to'kilish).", "hairgrowth"),
    Q("t9", "teri", "Kuniga qancha soch to'kilishi normal hisoblanadi?",
      ["50–100 ta", "1000 tagacha", "5–10 ta", "Umuman to'kilmasligi kerak"],
      "Kuniga 50–100 ta soch to'kilishi — tabiiy yangilanish jarayoni.", "hairgrowth"),
    Q("t10", "teri", "\"G'oz terisi\" (eti junjikishi)ni nima hosil qiladi?",
      ["Soch ko'taruvchi muskul", "Ter bezlari", "Yog' bezlari", "Melanotsitlar"],
      "Sovuq yoki qo'rquvda soch ko'taruvchi silliq muskul qisqarib, tukni tik turg'izadi.", "arrector"),
    Q("t11", "teri", "Qo'l tirnog'i qanday tezlikda o'sadi?",
      ["Oyiga ~3 mm", "Oyiga ~3 sm", "Yiliga ~3 mm", "Kuniga ~3 mm"],
      "Qo'l tirnog'i oyiga ~3 mm, oyoq tirnog'i esa ~1 mm o'sadi.", "nails"),
    Q("t12", "teri", "Ona qornidagi homila tanasini qoplaydigan mayin tuk nima deyiladi?",
      ["Lanugo", "Vellus", "Terminal tuk", "Kiprik"],
      "Lanugo 5-oydan paydo bo'ladi va odatda tug'ilishdan oldin to'kiladi.", "hairtypes"),
    Q("t13", "teri", "Teri quyosh nuri ta'sirida qaysi vitaminni hosil qiladi?",
      ["D vitamini", "C vitamini", "A vitamini", "B12 vitamini"],
      "UF nurlar ta'sirida terida D vitamini hosil bo'ladi — u suyaklar uchun zarur.", "skinfunc"),

    # ───────────── 🦴 Suyaklar ─────────────
    Q("s1", "suyak", "Katta yoshli odamda nechta suyak bor?", ["206 ta", "300 ta", "186 ta", "250 ta"],
      "Kattalarda 206 ta suyak bor; chaqaloqda ~270–300 ta, keyin ko'plari qo'shilib ketadi."),
    Q("s2", "suyak", "Tanadagi eng uzun suyak qaysi?",
      ["Son suyagi", "Katta boldir suyagi", "Yelka suyagi", "To'sh suyagi"],
      "Son suyagi (femur) bo'yning ~1/4 qismi, u eng uzun va eng mustahkam suyak.", "femur"),
    Q("s3", "suyak", "Tanadagi eng kichik suyak qaysi?",
      ["Uzangi", "Bolg'acha", "No'xatsimon suyak", "Ko'z yosh suyagi"],
      "Uzangi — o'rta quloqdagi suyakcha, uzunligi ~3 mm.", "ossicles"),
    Q("s4", "suyak", "Hech bir suyak bilan bo'g'im hosil qilmaydigan yagona suyak qaysi?",
      ["Til osti suyagi", "Dum suyagi", "Tizza qopqog'i", "Uzangi"],
      "Til osti suyagi faqat muskul va boylamlar bilan \"osilib\" turadi.", "hyoidb"),
    Q("s5", "suyak", "Odamda nechta qovurg'a bor?", ["24 ta (12 juft)", "22 ta", "26 ta", "20 ta"],
      "12 juft qovurg'a: 7 juft chin, 3 juft soxta, 2 juft erkin. Erkak va ayolda bir xil!", "ribs"),
    Q("s6", "suyak", "Bo'yinda nechta umurtqa bor?", ["7 ta", "12 ta", "5 ta", "9 ta"],
      "7 ta bo'yin umurtqasi bor — hatto jirafada ham 7 ta!", "cervical"),
    Q("s7", "suyak", "Kallaning yagona harakatchan suyagi qaysi?",
      ["Pastki jag'", "Yuqori jag'", "Ensa suyagi", "Chakka suyagi"],
      "Pastki jag' chakka-pastki jag' bo'g'imi orqali harakatlanadi; qolganlari choklar bilan birikkan.", "mandible"),
    Q("s8", "suyak", "Bitta qo'lda nechta kaft usti (karpal) suyagi bor?", ["8 ta", "5 ta", "14 ta", "7 ta"],
      "Har qo'lda 8 ta kaft usti suyagi, 2 qator bo'lib joylashgan.", "carpals"),
    Q("s9", "suyak", "Tanadagi eng harakatchan bo'g'im qaysi?",
      ["Yelka bo'g'imi", "Tizza bo'g'imi", "Son-chanoq bo'g'imi", "Tirsak bo'g'imi"],
      "Sharsimon yelka bo'g'imi barcha yo'nalishda harakatlanadi — shuning uchun eng ko'p chiqadi.", "shoulder"),
    Q("s10", "suyak", "Tanadagi eng katta va eng murakkab bo'g'im qaysi?",
      ["Tizza bo'g'imi", "Yelka bo'g'imi", "Son-chanoq bo'g'imi", "To'piq bo'g'imi"],
      "Tizza bo'g'imida meniskalar va xochsimon boylamlar bor.", "knee"),
    Q("s11", "suyak", "Bosh barmoq asosidagi bo'g'im qanday shaklda?",
      ["Egarsimon", "Sharsimon", "G'altaksimon", "Yassi"],
      "Egarsimon bo'g'im bosh barmoqni boshqa barmoqlarga qarama-qarshi qo'yish imkonini beradi.", "metacarpals"),
    Q("s12", "suyak", "Qon hujayralari qayerda ishlab chiqariladi?",
      ["Qizil suyak ko'migida", "Sariq suyak ko'migida", "Suyak usti pardasida", "Tog'ayda"],
      "Qizil ko'mik sekundiga ~2 million eritrotsit ishlab chiqaradi.", "bonestruct"),
    Q("s13", "suyak", "Ona qornida birinchi bo'lib suyaklanadigan suyak qaysi?",
      ["O'mrov suyagi", "Son suyagi", "To'sh suyagi", "Pastki jag'"],
      "O'mrov suyagi homilaning 5–6-haftasida birinchi bo'lib suyaklana boshlaydi.", "clavicle"),
    Q("s14", "suyak", "Bitta oyoq panjasida nechta suyak bor?", ["26 ta", "14 ta", "31 ta", "19 ta"],
      "Oyoq panjasi: 7 kaft usti + 5 kaft + 14 falanga = 26 ta suyak.", "metatarsals"),

    # ───────────── 🫘 Buyrak ─────────────
    Q("b1", "buyrak", "Buyraklar sutkasiga qancha birlamchi siydik filtrlaydi?",
      ["~180 litr", "~1,5 litr", "~18 litr", "~1800 litr"],
      "~180 litr filtrlanadi, lekin deyarli hammasi qayta so'riladi.", "nephron"),
    Q("b2", "buyrak", "Sog'lom odam sutkasiga qancha siydik ajratadi?",
      ["~1,5 litr", "~180 litr", "~0,1 litr", "~10 litr"],
      "Birlamchi siydikning atigi ~1% i — ~1,5 litri tashqariga chiqadi.", "kidney"),
    Q("b3", "buyrak", "Buyrakning tuzilish va funksional birligi nima?",
      ["Nefron", "Neyron", "Alveola", "Gepatotsit"],
      "Nefron — koptokcha va kanalchalardan iborat; neyron esa nerv hujayrasi.", "nephron"),
    Q("b4", "buyrak", "Bitta buyrakda taxminan nechta nefron bor?",
      ["~1 million", "~1000 ta", "~1 milliard", "~100 ta"],
      "Har bir buyrakda ~1 million nefron bor.", "nephron"),
    Q("b5", "buyrak", "Buyrak qon hosil bo'lishini qaysi gormon orqali rag'batlantiradi?",
      ["Eritropoetin", "Insulin", "Adrenalin", "Tiroksin"],
      "Eritropoetin suyak ko'migida eritrotsitlar hosil bo'lishini kuchaytiradi.", "ckd"),
    Q("b6", "buyrak", "Surunkali buyrak yetishmovchiligining eng ko'p uchraydigan sababi?",
      ["Qandli diabet", "Sistit", "Kamqonlik", "Gipotireoz"],
      "Yuqori qand koptokchalarni yemiradi; ikkinchi asosiy sabab — gipertoniya.", "ckd"),
    Q("b7", "buyrak", "Buyrak toshining oldini olishning eng oddiy usuli?",
      ["Kuniga 2–2,5 litr suv ichish", "Ko'proq tuz yeyish", "Suvni cheklash", "Kam harakat qilish"],
      "Suv kam bo'lsa siydik quyuqlashib, tuzlar kristallanadi.", "stones"),
    Q("b8", "buyrak", "Glomerulonefrit ko'pincha nimadan 2–3 hafta keyin boshlanadi?",
      ["Angina (streptokokk infeksiyasi)", "Suyak sinishi", "Kamqonlik", "Quyosh urishi"],
      "Immun tizim xato qilib koptokchalarga hujum qiladi — shuning uchun anginani to'liq davolash muhim.", "glomerulo"),
    Q("b9", "buyrak", "Nega sistit ayollarda ko'proq uchraydi?",
      ["Siydik chiqarish kanali kalta (3–5 sm)", "Buyragi kichikroq", "Siydik pufagi kattaroq", "Ko'p suv ichishadi"],
      "Kalta kanal orqali bakteriyalar pufakka oson ko'tariladi.", "cystitis"),
    Q("b10", "buyrak", "Siydik pufagining odatiy hajmi qancha?",
      ["350–500 ml", "~50 ml", "~2 litr", "~5 litr"],
      "250–300 ml to'planganda siyish istagi paydo bo'ladi.", "bladder"),
    Q("b11", "buyrak", "\"Buyrak sanchig'i\" — o'ta kuchli og'riqning sababi nima?",
      ["Tosh siydik yo'liga tiqilishi", "Sistit", "Gipertoniya", "Kamqonlik"],
      "Tosh siydik yo'lining tor joylarida tiqilib, kuchli spazm va og'riq beradi.", "ureter"),
    Q("b12", "buyrak", "Siydik yo'li (ureter) uzunligi taxminan qancha?",
      ["25–30 sm", "3–5 sm", "1 metr", "10 sm"],
      "Siydik yo'li buyrak jomidan siydik pufagigacha 25–30 sm.", "ureter"),

    # ───────────── ❤️ Qon aylanish ─────────────
    Q("q1", "qon", "Yurak necha kameradan iborat?", ["4 ta", "2 ta", "3 ta", "6 ta"],
      "2 bo'lmacha va 2 qorincha.", "heart"),
    Q("q2", "qon", "Katta yoshli odamda qancha qon bor?",
      ["4,5–5,5 litr", "1–2 litr", "~10 litr", "~0,5 litr"],
      "Qon tana vaznining ~7–8% ini tashkil etadi.", "blood"),
    Q("q3", "qon", "Eritrotsit (qizil qon tanachasi) qancha yashaydi?",
      ["~120 kun", "~1 kun", "~1 yil", "~10 kun"],
      "Eritrotsitlar ~120 kun yashaydi, so'ng taloq va jigarda parchalanadi.", "blood"),
    Q("q4", "qon", "Qonda kislorodni nima tashiydi?",
      ["Gemoglobin", "Fibrinogen", "Insulin", "Kollagen"],
      "Eritrotsitlardagi temirli oqsil — gemoglobin kislorodni biriktirib oladi.", "blood"),
    Q("q5", "qon", "Qon ivishini qaysi hujayralar ta'minlaydi?",
      ["Trombotsitlar", "Eritrotsitlar", "Leykotsitlar", "Limfotsitlar"],
      "Trombotsitlar jarohat joyida yopishib, laxta hosil qiladi.", "blood"),
    Q("q6", "qon", "Yurakning qaysi kamerasi devori eng qalin?",
      ["Chap qorincha", "O'ng qorincha", "Chap bo'lmacha", "O'ng bo'lmacha"],
      "Chap qorincha qonni butun tanaga haydaydi — devori 10–15 mm.", "heart"),
    Q("q7", "qon", "Yurak ritmini boshlab beruvchi \"tabiiy kardiostimulyator\" qaysi?",
      ["Sinus tuguni", "Gis tutami", "Purkine tolalari", "Mitral klapan"],
      "Sinus tuguni daqiqasiga 60–80 impuls hosil qiladi.", "conduction"),
    Q("q8", "qon", "Qonni yurakdan OLIB KETADIGAN tomirlar qanday ataladi?",
      ["Arteriyalar", "Venalar", "Kapillyarlar", "Limfa tomirlari"],
      "Arteriyalar — yurakdan, venalar — yurakka.", "aorta"),
    Q("q9", "qon", "Normal arterial qon bosimi taxminan qancha?",
      ["~120/80 mm sim. ust.", "~180/110", "~90/40", "~200/120"],
      "140/90 va undan yuqori bo'lsa — gipertoniya.", "hypertension"),
    Q("q10", "qon", "Miokard infarkti nima?",
      ["Yurak muskulining bir qismi qonsiz qolib nobud bo'lishi", "Miya tomirining yorilishi",
       "Oyoq venasida qon laxtasi", "Yurak klapanining torayishi"],
      "Toj arteriyasi tiqilib, yurak muskuli qonsiz qoladi. Darhol 103 ga qo'ng'iroq qiling!", "infarct"),
    Q("q11", "qon", "Kamqonlikning (anemiya) eng ko'p uchraydigan sababi?",
      ["Temir yetishmasligi", "Ko'p suv ichish", "Yuqori qon bosimi", "C vitamini ortiqchaligi"],
      "Temir gemoglobin tarkibiga kiradi; u yetishmasa gemoglobin kamayadi.", "anemia"),
    Q("q12", "qon", "Qaysi belgi insultni ko'rsatadi?",
      ["Yuzning bir tomoni osilishi va nutq buzilishi", "Oyoqlar shishishi", "Tez-tez siyish",
       "Ko'zlar chaqchayishi"],
      "\"Yuz-qo'l-nutq\" testi: yuz qiyshayishi, qo'l kuchsizligi, nutq buzilishi — darhol 103!", "stroke"),
    Q("q13", "qon", "Katta odamda tinch holatdagi normal puls?",
      ["Daqiqasiga 60–90", "Daqiqasiga 20–30", "Daqiqasiga 150–180", "Daqiqasiga 100–140"],
      "Normal puls 60–90 zarba/daqiqa.", "conduction"),

    # ───────────── 🧪 Bezlar va gormonlar ─────────────
    Q("g1", "bez", "Qaysi bez \"bezlar qiroli\" deb ataladi?",
      ["Gipofiz", "Qalqonsimon bez", "Epifiz", "Buyrak usti bezi"],
      "Gipofiz TTG, AKTG, FSG, LG orqali boshqa bezlarni boshqaradi.", "pituitary"),
    Q("g2", "bez", "Qondagi qandni KAMAYTIRUVCHI gormon qaysi?",
      ["Insulin", "Glyukagon", "Adrenalin", "Kortizol"],
      "Insulin glyukozani hujayralarga kiritadi; glyukagon, adrenalin, kortizol esa qandni oshiradi.", "pancreas"),
    Q("g3", "bez", "Insulinni qaysi hujayralar ishlab chiqaradi?",
      ["Langergans orolchalarining β-hujayralari", "Orolchalarning α-hujayralari", "Gipofiz hujayralari",
       "Buyrak usti bezi hujayralari"],
      "β-hujayralar — insulin, α-hujayralar — glyukagon.", "pancreas"),
    Q("g4", "bez", "Qalqonsimon bez gormonlari tarkibida qaysi element bor?",
      ["Yod", "Temir", "Kalsiy", "Natriy"],
      "Tiroksin (T4) va triyodtironin (T3) tarkibida yod bor.", "thyroid"),
    Q("g5", "bez", "Endemik buqoqning asosiy sababi nima?",
      ["Yod yetishmasligi", "Temir yetishmasligi", "Ortiqcha kalsiy", "Ortiqcha shakar"],
      "Oldini olish uchun yodlangan tuz ishlatish kerak.", "goiter"),
    Q("g6", "bez", "\"Uyqu gormoni\" qaysi?", ["Melatonin", "Adrenalin", "Insulin", "Testosteron"],
      "Melatonin qorong'ida ko'payadi; kechasi ekran yorug'i uni kamaytiradi.", "pineal"),
    Q("g7", "bez", "Melatoninni qaysi bez ishlab chiqaradi?",
      ["Epifiz", "Gipofiz", "Ayrisimon bez", "Qalqonsimon bez"],
      "Epifiz (shishsimon bez) miya markazida joylashgan.", "pineal"),
    Q("g8", "bez", "Bolalikda o'sish gormoni ORTIQCHA bo'lsa nima rivojlanadi?",
      ["Gigantizm", "Kretinizm", "Pakanalik", "Qandli diabet"],
      "Bolalikda — gigantizm, kattalarda — akromegaliya; kam bo'lsa — pakanalik.", "growthdis"),
    Q("g9", "bez", "Bazedov kasalligining (tireotoksikoz) xos belgisi qaysi?",
      ["Ko'z chaqchayishi va ozib ketish", "Semirish va uyquchanlik", "Teri bronza rangiga kirishi",
       "Bo'y o'smay qolishi"],
      "Qalqonsimon bez gormoni ko'p — moddalar almashinuvi juda tezlashadi.", "graves"),
    Q("g10", "bez", "Kortizol ORTIQCHA bo'lganda qaysi kasallik kelib chiqadi?",
      ["Itsenko-Kushing sindromi", "Addison kasalligi", "Gipotireoz", "Akromegaliya"],
      "Kortizol kam bo'lsa — Addison (bronza) kasalligi.", "cushing"),
    Q("g11", "bez", "Adrenalin qayerda ishlab chiqariladi?",
      ["Buyrak usti bezining mag'iz qavatida", "Gipofizda", "Oshqozon osti bezida", "Qalqonsimon bezda"],
      "Buyrak usti bezi mag'izi — adrenalin va noradrenalin, po'stlog'i — kortizol va aldosteron.", "adrenal"),
    Q("g12", "bez", "Qondagi kalsiyni OSHIRUVCHI gormon qaysi?",
      ["Paratgormon", "Kalsitonin", "Insulin", "Melatonin"],
      "Paratgormon kalsiyni oshiradi, kalsitonin esa kamaytiradi.", "parathyroid"),
    Q("g13", "bez", "1-tur qandli diabetda nima bo'ladi?",
      ["Insulin umuman ishlab chiqarilmaydi", "Insulin juda ko'p ishlab chiqariladi", "Yod yetishmaydi",
       "Kortizol kamayadi"],
      "Immun tizim β-hujayralarni yemiradi — davolash umrbod insulin ukoli.", "diabetes"),
    Q("g14", "bez", "Och qoringa qondagi qandning normal miqdori?",
      ["3,3–5,5 mmol/l", "10–15 mmol/l", "0,5–1 mmol/l", "20 mmol/l dan yuqori"],
      "Och qoringa 7 mmol/l dan yuqori bo'lsa — diabetga shubha.", "pancreas"),
    Q("g15", "bez", "Qandsiz diabet qaysi gormon yetishmasligidan kelib chiqadi?",
      ["ADG (vazopressin)", "Insulin", "Tiroksin", "Estrogen"],
      "ADG yetishmasa buyrak suvni ushlab qololmaydi — sutkasiga 5–20 litr siydik ajraladi.", "hypothal"),
]

BY_ID = {q["id"]: q for q in QUESTIONS}
